name: Upload to Google Cloud Storage

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  job_upload_to_gcs:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
  
    steps:
    - id: 'checkout'
      uses: 'actions/checkout@v4'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - id: 'upload-file'
      uses: 'hdwarakanath/upload-cloud-storage@main'
      with:
        path: 'hd_sample_data.txt'
        destination: 'hd-artifacts/actions/output/'
        project_id: 'trup-amex-prod'
        process_gcloudignore: false
